package ch.fhnw.compiler;

public enum Terminals {
 LITERAL,IDENT,LEXERROR,RELOPR,
 BOOLOPR,TYPE,SENTINEL,ADDOPR,MULTOPR,BOOL,INT64,
 LPAREN,RPAREN,COMMA,SEMICOLON,COLON,BECOMES,FLOWMODE,CHANGEMODE,MECHMODE
}
